<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "liquid"
 *
 * Auto generated by Extension Builder 2014-06-25
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Liquid - Fluid styled content',
	'description' => 'Styled content for the default content elements made with extbase and fluid',
	'category' => 'plugin',
	'author' => 'Martin Sonnenholzer',
	'author_email' => 'martin.sonnenholzer@googlemail.com',
	'author_company' => '',
	'shy' => '',
	'priority' => '',
	'module' => '',
	'state' => 'experimental',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'modify_tables' => '',
	'clearCacheOnLoad' => 0,
	'lockType' => '',
	'version' => '0.1.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '6.2',
		),
		'conflicts' => array(
		),
		'suggests' => array(
		),
	),
);